### ISSUE TITLE
use server embedder (inception v3 etc) models offline 

### ISSUE THREAD

**Issue by NUSTemple** [biolab/orange3-imageanalytics#173]
##### Image Analytics version

0.4.1

##### Orange version

3.23.1

##### Expected behavior
Server models like inception v3, VGG-19 can be used offline

##### Actual behavior
My computer is configured with proxy and cannot access api.garaza.io:443. Hence I cannot dowload required models. 

##### Additional info (worksheets, data, screenshots, ...)
![image](https://user-images.githubusercontent.com/17231710/71335566-40b60880-257e-11ea-883c-828c6b029903.png)

**Comment by ajdapretnar** [comment]
I must admit, I don't understand the issue fully.
First, server model's *can't* be used offline. They're server-based, it's in their nature.
Second, you must set your proxy settings correctly. You can do that in Options - Settings - Networks.
Alternatively, please better explain the issue.

**Comment by PrimozGodec** [comment]
Other embedders cannot be local since they are too slow. At the server, they run in parallel. Since we wanted to provide an option for users for not sending images to the server there is SqueezeNet implementation that runs locally (and performs well). 

We are also aware that there is a problem with accessing our server through the proxy (even proxy server is correctly set up with Orange). It happens due to buggy implementation in a Hyper library which is used to communicate with the server. Due to this and a few other issues with Hyper (it is not maintained anymore) we are now implementing a client with other library HTTPX (https://github.com/biolab/orange3-imageanalytics/pull/162) we hope that we can solve the proxy problem with the new library.

**Comment by NUSTemple** [comment]
Thanks both for the reply. Appreciate that help. I am now using orange behind the proxy and currently api.garaza.io is blocked. Instead, we have a standalone GPU cluster which can be used to train the model itself. Thinking whether we can make this url as a configuration input and we can put our own server name there. Thanks.

**Comment by PrimozGodec** [comment]
It is actually implemented already here: https://github.com/biolab/orange3-imageanalytics/pull/114 It is not merged since we didn't have an opportunity to test it properly. If you want to use it pull this pull request. The server needs to be configured such that it responds to the request (image) with a vector of embeddings.

**Comment by PrimozGodec** [comment]
We will merge this PR with the custom server settings in master when we finish the transition to httpx.
