### ISSUE TITLE
Where is the Import button for text-ming?

### ISSUE THREAD

**Issue by PascaleUdeM** [biolab/orange3-imageanalytics#177]
Orange version: 3.24

Hi! I downloaded the text-mining add-on. But in the text-mining zone, there is no Import document button like I saw in the tutorial on YouTube. Could you help me? I want to import some PDF documents.
I work on Windows 10 with Orange version 3.24.
![textemining-issue](https://user-images.githubusercontent.com/61889980/76125050-fdd6cf00-5fc9-11ea-96ff-09bfc139a470.jpg)

**Comment by PrimozGodec** [comment]
Sorry for the delay. This issue is more suitable to [text addon](https://github.com/biolab/orange3-text).
Can you please move this widget there?

Besides, I would also ask if you can run orange with Command line:
1. Go to place where Orange is installed. By default, it is `C:\Users\<you username>\AppData\Local\Orange`
2. Click Orange Debug
3. When Orange opens copy test from the Command Line and past it to the issue. 

This text usually tells the reason why widget is not shown.
