### ISSUE TITLE
Mis-matching value of image embeddings between keras and orange

### ISSUE THREAD

**Issue by gvkalra** [biolab/orange3-imageanalytics#96]
Hi,

Thanks for a beautiful software!

I am having problems with obtaining same values
of Image Embeddings in Orange as reported by Keras.

##### Image Analytics version
0.1.16

##### Orange version
3.10.0.dev0+f05be54

##### Expected behavior
Image embeddings in Orange should match results in Keras

##### Actual behavior
Mis-matching value of image embeddings

##### Steps to reproduce the behavior
1. Obtain image embedding in Orange for [this](https://avatars2.githubusercontent.com/u/498380) image
2. Obtain image embedding in Keras using the same image using [this](https://gist.github.com/gvkalra/243d65cc1954fa486edb1a43d08c499c) code.

##### First few values in Orange
[0] = 0.337
[1] = 0.261
[2] = 0.126
[3] = 0.332
[4] = 0.006

##### First few values in Keras
[0] = 0.200292
[1] = 0.163431
[2] = 0.1735
[3] = 0.936602
[4] = 0.408029

**Comment by gvkalra** [comment]
CC/ @minhresl

**Comment by PrimozGodec** [comment]
On [fchollet/deep-learning-models](https://github.com/fchollet/deep-learning-models), repository where Keras weights are available, I found this, `The Inception v3 weights are trained by ourselves and are released under the MIT license`, while we are using [Tensorflow weights](http://download.tensorflow.org/models/image/imagenet/inception-2015-12-05.tgz).

I think since weights are retrieved from the different training they can have different penultimate layer values.

**Comment by gvkalra** [comment]
Thanks! Although I can't verify it now, the reason seems to be legit.
